component_depth: 3
exclude:
- /binaries/.*
- /build/.*
- /docs/.*
- /libraries/.*
- /source/.collada
- /source/.gui
- /source/.i18n
- /source/.lib
- /source/.lobby
- /source/.maths
- /source/.mocks
- /source/.network
- /source/.pch
- /source/.ps
- /source/.renderer
- /source/.scriptinterface
- /source/.simulation2
- /source/.soundmanager
- /source/.third_party
- /source/.tools